copy mar_c11_akuwarai1.png mar_akuwaraia1.png
copy mar_c22_akuwarai2.png mar_akuwaraia2.png
copy mar_c12_akuwarai2.png mar_akuwaraia3.png
copy mar_c12_def1.png mar_defa1.png
copy mar_c22_def1k.png mar_defa1k.png
copy mar_c12_fukigen2.png mar_fukigena1.png
copy mar_c12_fukigen2.png mar_fukigena2.png
copy mar_c11_ikari1.png mar_ikaria1.png
copy mar_c22_ikari1.png mar_ikaria2.png
copy mar_c12_fukigen2.png mar_komarua1.png
copy mar_c22_majime1.png mar_majimea1.png
copy mar_c23_naku1.png mar_nakua1.png
copy mar_c21_niyari1.png mar_niyaria1.png
copy mar_c11_niyari1.png mar_niyaria2.png
copy mar_c11_odoroki1.png mar_odorokia1.png
copy mar_c22_sakebu1.png mar_sakebua1.png
copy mar_c21_warai1.png mar_waraia1.png
copy mar_c21_warai2.png mar_waraia2.png
pause